# This file was generated with the command (and manually edited :p):
# "gni-to-cmake.py" "src/tests/angle_end2end_tests.gni" "angle_end2end_tests.cmake" "--prepend" "src/tests/"

# Copyright 2014 The ANGLE Project Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set(angle_end2end_tests_sources
    # "src/tests/egl_tests/EGLAndroidFrameBufferTargetTest.cpp"
    # "src/tests/egl_tests/EGLBackwardsCompatibleContextTest.cpp"
    # "src/tests/egl_tests/EGLBlobCacheTest.cpp"
    # "src/tests/egl_tests/EGLBufferAgeTest.cpp"
    # "src/tests/egl_tests/EGLChooseConfigTest.cpp"
    # "src/tests/egl_tests/EGLContextASANTest.cpp"
    "src/tests/egl_tests/EGLContextCompatibilityTest.cpp"
    # "src/tests/egl_tests/EGLContextSharingTest.cpp"
    # "src/tests/egl_tests/EGLCreateContextAttribsTest.cpp"
    # "src/tests/egl_tests/EGLDebugTest.cpp"
    # "src/tests/egl_tests/EGLDisplaySelectionTest.cpp"
    # "src/tests/egl_tests/EGLDisplayTest.cpp"
    # "src/tests/egl_tests/EGLLockSurface3Test.cpp"
    # "src/tests/egl_tests/EGLMultiContextTest.cpp"
    # "src/tests/egl_tests/EGLNoConfigContextTest.cpp"
    # "src/tests/egl_tests/EGLPreRotationTest.cpp"
    # "src/tests/egl_tests/EGLPrintEGLinfoTest.cpp"
    # "src/tests/egl_tests/EGLProgramCacheControlTest.cpp"
    # "src/tests/egl_tests/EGLProtectedContentTest.cpp"
    # "src/tests/egl_tests/EGLQueryContextTest.cpp"
    # "src/tests/egl_tests/EGLReadinessCheckTest.cpp"
    # "src/tests/egl_tests/EGLRecordableTest.cpp"
    # "src/tests/egl_tests/EGLRobustnessTest.cpp"
    # "src/tests/egl_tests/EGLSurfaceTest.cpp"
    # "src/tests/egl_tests/EGLSurfacelessContextTest.cpp"
    # "src/tests/egl_tests/EGLSyncTest.cpp"
    # "src/tests/gl_tests/ActiveTextureCacheTest.cpp"
    # "src/tests/gl_tests/AtomicCounterBufferTest.cpp"
    # "src/tests/gl_tests/AttributeLayoutTest.cpp"
    # "src/tests/gl_tests/BPTCCompressedTextureTest.cpp"
    # "src/tests/gl_tests/BindGeneratesResourceTest.cpp"
    # "src/tests/gl_tests/BindUniformLocationTest.cpp"
    # "src/tests/gl_tests/BlendFuncExtendedTest.cpp"
    # "src/tests/gl_tests/BlendIntegerTest.cpp"
    # "src/tests/gl_tests/BlendMinMaxTest.cpp"
    # "src/tests/gl_tests/BlendPackedTest.cpp"
    # "src/tests/gl_tests/BlitFramebufferANGLETest.cpp"
    # "src/tests/gl_tests/BufferDataTest.cpp"
    # "src/tests/gl_tests/BuiltinVariableTest.cpp"
    "src/tests/gl_tests/ClearTest.cpp"
    # "src/tests/gl_tests/ClientArraysTest.cpp"
    # "src/tests/gl_tests/ClipControlTest.cpp"
    # "src/tests/gl_tests/ClipDistanceTest.cpp"
    # "src/tests/gl_tests/ColorMaskTest.cpp"
    # "src/tests/gl_tests/CompressedTextureFormatsTest.cpp"
    # "src/tests/gl_tests/ComputeShaderTest.cpp"
    # "src/tests/gl_tests/ContextLostTest.cpp"
    # "src/tests/gl_tests/ContextNoErrorTest.cpp"
    # "src/tests/gl_tests/CopyCompressedTextureTest.cpp"
    # "src/tests/gl_tests/CopyTexImageTest.cpp"
    # "src/tests/gl_tests/CopyTexture3DTest.cpp"
    # "src/tests/gl_tests/CopyTextureTest.cpp"
    # "src/tests/gl_tests/CubeMapTextureTest.cpp"
    # "src/tests/gl_tests/DXT1CompressedTextureTest.cpp"
    # "src/tests/gl_tests/DXTSRGBCompressedTextureTest.cpp"
    # "src/tests/gl_tests/DebugMarkerTest.cpp"
    # "src/tests/gl_tests/DebugTest.cpp"
    # "src/tests/gl_tests/DepthStencilFormatsTest.cpp"
    # "src/tests/gl_tests/DepthStencilTest.cpp"
    # "src/tests/gl_tests/DepthWriteTest.cpp"
    # "src/tests/gl_tests/DesktopGLSLTest.cpp"
    # "src/tests/gl_tests/DifferentStencilMasksTest.cpp"
    # "src/tests/gl_tests/DiscardFramebufferEXTTest.cpp"
    # "src/tests/gl_tests/DrawBaseVertexBaseInstanceTest.cpp"
    # "src/tests/gl_tests/DrawBaseVertexVariantsTest.cpp"
    # "src/tests/gl_tests/DrawBuffersTest.cpp"
    # "src/tests/gl_tests/DrawElementsTest.cpp"
    # "src/tests/gl_tests/DrawRangeElementsTest.cpp"
    # "src/tests/gl_tests/EGLImageMECFriendlyTest.cpp"
    # "src/tests/gl_tests/ETCTextureTest.cpp"
    # "src/tests/gl_tests/ExternalBufferTest.cpp"
    # "src/tests/gl_tests/ExternalWrapTest.cpp"
    # "src/tests/gl_tests/FenceSyncTests.cpp"
    # "src/tests/gl_tests/FloatingPointSurfaceTest.cpp"
    # "src/tests/gl_tests/FragDepthTest.cpp"
    # "src/tests/gl_tests/FramebufferFetchTest.cpp"
    # "src/tests/gl_tests/FramebufferMixedSamplesTest.cpp"
    # "src/tests/gl_tests/FramebufferMultiviewTest.cpp"
    # "src/tests/gl_tests/FramebufferRenderMipmapTest.cpp"
    # "src/tests/gl_tests/FramebufferTest.cpp"
    # "src/tests/gl_tests/GLSLTest.cpp"
    # "src/tests/gl_tests/GeometryShaderTest.cpp"
    # "src/tests/gl_tests/GetImageTest.cpp"
    # "src/tests/gl_tests/GetTexLevelParameterTest.cpp"
    # "src/tests/gl_tests/ImageTest.cpp"
    # "src/tests/gl_tests/IncompleteTextureTest.cpp"
    # "src/tests/gl_tests/IndexBufferOffsetTest.cpp"
    # "src/tests/gl_tests/IndexedPointsTest.cpp"
    # "src/tests/gl_tests/InstancingTest.cpp"
    # "src/tests/gl_tests/KTXCompressedTextureTest.cpp"
    # "src/tests/gl_tests/LineLoopTest.cpp"
    # "src/tests/gl_tests/LinkAndRelinkTest.cpp"
    # "src/tests/gl_tests/MatrixTest.cpp"
    # "src/tests/gl_tests/MaxTextureSizeTest.cpp"
    # "src/tests/gl_tests/MemoryBarrierTest.cpp"
    # "src/tests/gl_tests/MemoryObjectTest.cpp"
    # "src/tests/gl_tests/MemorySizeTest.cpp"
    # "src/tests/gl_tests/MipmapTest.cpp"
    # "src/tests/gl_tests/MultiDrawTest.cpp"
    # "src/tests/gl_tests/MultisampleCompatibilityTest.cpp"
    # "src/tests/gl_tests/MultisampleTest.cpp"
    # "src/tests/gl_tests/MultisampledRenderToTextureTest.cpp"
    # "src/tests/gl_tests/MultithreadingTest.cpp"
    # "src/tests/gl_tests/MultiviewDrawTest.cpp"
    # "src/tests/gl_tests/ObjectAllocationTest.cpp"
    # "src/tests/gl_tests/OcclusionQueriesTest.cpp"
    # "src/tests/gl_tests/PBOExtensionTest.cpp"
    # "src/tests/gl_tests/PackUnpackTest.cpp"
    # "src/tests/gl_tests/ParallelShaderCompileTest.cpp"
    # "src/tests/gl_tests/PbufferTest.cpp"
    # "src/tests/gl_tests/PixelLocalStorageTest.cpp"
    # "src/tests/gl_tests/PixmapTest.cpp"
    # "src/tests/gl_tests/PointSpritesTest.cpp"
    # "src/tests/gl_tests/PolygonOffsetClampTest.cpp"
    # "src/tests/gl_tests/ProgramBinaryTest.cpp"
    # "src/tests/gl_tests/ProgramInterfaceTest.cpp"
    # "src/tests/gl_tests/ProgramParameterTest.cpp"
    # "src/tests/gl_tests/ProgramPipelineTest.cpp"
    # "src/tests/gl_tests/ProvokingVertexTest.cpp"
    # "src/tests/gl_tests/QueryObjectValidation.cpp"
    # "src/tests/gl_tests/ReadOnlyFeedbackLoopTest.cpp"
    # "src/tests/gl_tests/ReadPixelsTest.cpp"
    # "src/tests/gl_tests/RenderbufferMultisampleTest.cpp"
    # "src/tests/gl_tests/RendererTest.cpp"
    # "src/tests/gl_tests/RequestExtensionTest.cpp"
    # "src/tests/gl_tests/RobustBufferAccessBehaviorTest.cpp"
    # "src/tests/gl_tests/RobustClientMemoryTest.cpp"
    # "src/tests/gl_tests/RobustFragmentShaderOutputTest.cpp"
    # "src/tests/gl_tests/RobustResourceInitTest.cpp"
    # "src/tests/gl_tests/S3TCTextureSizesTest.cpp"
    # "src/tests/gl_tests/SRGBFramebufferTest.cpp"
    # "src/tests/gl_tests/SRGBTextureTest.cpp"
    # "src/tests/gl_tests/SampleVariablesTest.cpp"
    # "src/tests/gl_tests/SamplersTest.cpp"
    # "src/tests/gl_tests/SemaphoreTest.cpp"
    # "src/tests/gl_tests/ShaderAlgorithmTest.cpp"
    # "src/tests/gl_tests/ShaderBinaryTest.cpp"
    # "src/tests/gl_tests/ShaderInterpTest.cpp"
    # "src/tests/gl_tests/ShaderMultisampleInterpolation.cpp"
    # "src/tests/gl_tests/ShaderNonConstGlobalInitializerTest.cpp"
    # "src/tests/gl_tests/ShaderStorageBufferTest.cpp"
    # "src/tests/gl_tests/ShadingRateQcomTest.cpp"
    # "src/tests/gl_tests/SimpleOperationTest.cpp"
    # "src/tests/gl_tests/SixteenBppTextureTest.cpp"
    # "src/tests/gl_tests/StateChangeTest.cpp"
    # "src/tests/gl_tests/SwizzleTest.cpp"
    # "src/tests/gl_tests/SyncQueriesTest.cpp"
    # "src/tests/gl_tests/TextureExternalUpdateTest.cpp"
    # "src/tests/gl_tests/TextureFilteringHintTest.cpp"
    # "src/tests/gl_tests/TextureMultisampleTest.cpp"
    # "src/tests/gl_tests/TextureRectangleTest.cpp"
    # "src/tests/gl_tests/TextureTest.cpp"
    # "src/tests/gl_tests/TextureUploadFormatTest.cpp"
    # "src/tests/gl_tests/TimerQueriesTest.cpp"
    # "src/tests/gl_tests/TransformFeedbackTest.cpp"
    # "src/tests/gl_tests/UniformBufferTest.cpp"
    # "src/tests/gl_tests/UniformTest.cpp"
    # "src/tests/gl_tests/UnpackAlignmentTest.cpp"
    # "src/tests/gl_tests/UnpackRowLength.cpp"
    # "src/tests/gl_tests/VertexAttributeTest.cpp"
    # "src/tests/gl_tests/ViewportTest.cpp"
    # "src/tests/gl_tests/VulkanPerformanceCounterTest.cpp"
    # "src/tests/gl_tests/WEBGLVideoTextureTest.cpp"
    # "src/tests/gl_tests/WebGLCompatibilityTest.cpp"
    # "src/tests/gl_tests/WebGLCompressedTextureAvailabilityTest.cpp"
    # "src/tests/gl_tests/WebGLFramebufferTest.cpp"
    # "src/tests/gl_tests/WebGLReadOutsideFramebufferTest.cpp"
    # "src/tests/gl_tests/gles1/AlphaFuncTest.cpp"
    # "src/tests/gl_tests/gles1/BGRATextureTest.cpp"
    # "src/tests/gl_tests/gles1/BasicDrawTest.cpp"
    # "src/tests/gl_tests/gles1/BootAnimationTest.cpp"
    # "src/tests/gl_tests/gles1/ClientActiveTextureTest.cpp"
    # "src/tests/gl_tests/gles1/ClientStateEnable.cpp"
    # "src/tests/gl_tests/gles1/ClipPlaneTest.cpp"
    # "src/tests/gl_tests/gles1/ColorMaterialTest.cpp"
    # "src/tests/gl_tests/gles1/CurrentColorTest.cpp"
    # "src/tests/gl_tests/gles1/CurrentNormalTest.cpp"
    # "src/tests/gl_tests/gles1/CurrentTextureCoordsTest.cpp"
    # "src/tests/gl_tests/gles1/DrawTextureTest.cpp"
    # "src/tests/gl_tests/gles1/FogTest.cpp"
    # "src/tests/gl_tests/gles1/FramebufferObjectTest.cpp"
    # "src/tests/gl_tests/gles1/LightsTest.cpp"
    # "src/tests/gl_tests/gles1/MaterialsTest.cpp"
    # "src/tests/gl_tests/gles1/MatrixBuiltinsTest.cpp"
    # "src/tests/gl_tests/gles1/MatrixLoadTest.cpp"
    # "src/tests/gl_tests/gles1/MatrixModeTest.cpp"
    # "src/tests/gl_tests/gles1/MatrixMultTest.cpp"
    # "src/tests/gl_tests/gles1/MatrixStackTest.cpp"
    # "src/tests/gl_tests/gles1/PalettedTextureTest.cpp"
    # "src/tests/gl_tests/gles1/PointParameterTest.cpp"
    # "src/tests/gl_tests/gles1/PointSpriteTest.cpp"
    # "src/tests/gl_tests/gles1/ShadeModelTest.cpp"
    # "src/tests/gl_tests/gles1/TextureEnvTest.cpp"
    # "src/tests/gl_tests/gles1/TextureParameterTest.cpp"
    # "src/tests/gl_tests/gles1/TextureTargetEnableTest.cpp"
    # "src/tests/gl_tests/gles1/VertexPointerTest.cpp"
    # "src/tests/gl_tests/media/pixel.inc"
    # "src/tests/test_expectations/GPUTestExpectationsTest.cpp"
    "src/tests/test_utils/ANGLETest.cpp"
    "src/tests/test_utils/ANGLETest.h"
    "src/tests/test_utils/MultiviewTest.cpp"
    "src/tests/test_utils/MultiviewTest.h"
    "src/tests/test_utils/system_info_util.cpp"
    "src/tests/test_utils/system_info_util.h"
)

set(angle_end2end_tests_ios_sources "src/tests/egl_tests/EGLIOSurfaceClientBufferTest.cpp")

set(angle_end2end_tests_mac_sources
    "src/tests/egl_tests/EGLDeviceCGLTest.cpp"
    "src/tests/egl_tests/EGLIOSurfaceClientBufferTest.cpp"
    "src/tests/egl_tests/EGLPowerPreferenceTest.cpp"
    "src/tests/egl_tests/EGLSurfaceTestMac.mm"
    "src/tests/egl_tests/EGLSyncTestMetalSharedEvent.mm"
    "src/tests/egl_tests/EGLWaitUntilWorkScheduledTest.cpp"
    "src/tests/gl_tests/ImageTestMetal.mm"
)

set(angle_end2end_tests_win_sources
    "src/tests/egl_tests/EGLDeviceTest.cpp"
    "src/tests/egl_tests/EGLDisplayLuidTest.cpp"
    "src/tests/egl_tests/EGLPresentPathD3D11Test.cpp"
    "src/tests/egl_tests/EGLStreamTest.cpp"
    "src/tests/egl_tests/EGLSyncControlTest.cpp"
    "src/tests/egl_tests/media/yuvtest.inl"
    "src/tests/gl_tests/D3DImageFormatConversionTest.cpp"
)
